### ISSUE TITLE
Add source code of Performance example

### ISSUE THREAD

**Issue by ikruzeRlw** [ag-grid/ag-grid-demos#2]
Hi fellow, your work is incredible

I was looking for the source code of "Performance" example and it doesn't exist

Is there any chance to find it or push it into this repo?

Thank you

**Comment by markdurrant** [comment]
Hi @ikruzeRlw, thanks for such positive feedback!

Unfortunately the performance example is one of our legacy examples and we don't have a self contained version we're able to share at this time. 

It's on our roadmap to port the example over to this repo but I'm afraid I can't give you a firm date for that. 

Please 'watch' this repository to be notified when a new example is added.
